[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
num-traits = { version = "0.2.19", default-features = false }
rand = "0.9.2"
rayon = "1.11.0"

[profile.release]
debug = true
